// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Skill_Matrix.Data;

#nullable disable

namespace Skill_Matrix.Migrations
{
    [DbContext(typeof(SkillMatrixDbContext))]
    [Migration("20250826141807_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Skill_Matrix.Entities.Options", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuizQuestionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuizQuestionId");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("Skill_Matrix.Entities.QuizBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId");

                    b.ToTable("QuizBatches");
                });

            modelBuilder.Entity("Skill_Matrix.Entities.QuizQuestions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuizBatchId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuizBatchId");

                    b.ToTable("QuizQuestions");
                });

            modelBuilder.Entity("Skill_Matrix.Entities.QuizResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateTaken")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NoOfCorrectAnswers")
                        .HasColumnType("integer");

                    b.Property<int>("NoOfWrongAnswers")
                        .HasColumnType("integer");

                    b.Property<string>("ProficiencyLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("QuizBatchId")
                        .HasColumnType("integer");

                    b.Property<int>("RetakeCount")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuizBatchId")
                        .IsUnique();

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId");

                    b.ToTable("QuizResults");
                });

            modelBuilder.Entity("Skill_Matrix.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastAssessed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProficiencyLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Skill_Matrix.Entities.Suggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuizResultId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceLink")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.Property<string>("Suggestions")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuizResultId");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId");

                    b.ToTable("Suggestions");
                });

            modelBuilder.Entity("Skill_Matrix.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Skill_Matrix.Entities.WrongAnswers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerText")
                        .HasColumnType("text");

                    b.Property<int>("QuizBatchId")
                        .HasColumnType("integer");

                    b.Property<int>("QuizQuestionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuizBatchId");

                    b.HasIndex("QuizQuestionId");

                    b.ToTable("WrongAnswers");
                });

            modelBuilder.Entity("Skill_Matrix.Entities.Options", b =>
                {
                    b.HasOne("Skill_Matrix.Entities.QuizQuestions", "QuizQuestion")
                        .WithMany("Options")
                        .HasForeignKey("QuizQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuizQuestion");
                });

            modelBuilder.Entity("Skill_Matrix.Entities.QuizBatch", b =>
                {
                    b.HasOne("Skill_Matrix.Entities.Skill", "Skill")
                        .WithMany("QuizBatches")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Skill_Matrix.Entities.User", "User")
                        .WithMany("QuizBatches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Skill_Matrix.Entities.QuizQuestions", b =>
                {
                    b.HasOne("Skill_Matrix.Entities.QuizBatch", "QuizBatch")
                        .WithMany("Questions")
                        .HasForeignKey("QuizBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuizBatch");
                });

            modelBuilder.Entity("Skill_Matrix.Entities.QuizResult", b =>
                {
                    b.HasOne("Skill_Matrix.Entities.QuizBatch", "QuizBatch")
                        .WithOne("Result")
                        .HasForeignKey("Skill_Matrix.Entities.QuizResult", "QuizBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Skill_Matrix.Entities.Skill", "Skill")
                        .WithMany("QuizResults")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Skill_Matrix.Entities.User", "User")
                        .WithMany("QuizResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuizBatch");

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Skill_Matrix.Entities.Skill", b =>
                {
                    b.HasOne("Skill_Matrix.Entities.User", "User")
                        .WithMany("Skills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Skill_Matrix.Entities.Suggestion", b =>
                {
                    b.HasOne("Skill_Matrix.Entities.QuizResult", "QuizResult")
                        .WithMany("Suggestions")
                        .HasForeignKey("QuizResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Skill_Matrix.Entities.Skill", "Skill")
                        .WithMany("Suggestions")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Skill_Matrix.Entities.User", "User")
                        .WithMany("Suggestions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuizResult");

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Skill_Matrix.Entities.WrongAnswers", b =>
                {
                    b.HasOne("Skill_Matrix.Entities.QuizBatch", "QuizBatch")
                        .WithMany("WrongAnswers")
                        .HasForeignKey("QuizBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Skill_Matrix.Entities.QuizQuestions", "QuizQuestion")
                        .WithMany("WrongAnswers")
                        .HasForeignKey("QuizQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuizBatch");

                    b.Navigation("QuizQuestion");
                });

            modelBuilder.Entity("Skill_Matrix.Entities.QuizBatch", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Result")
                        .IsRequired();

                    b.Navigation("WrongAnswers");
                });

            modelBuilder.Entity("Skill_Matrix.Entities.QuizQuestions", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("WrongAnswers");
                });

            modelBuilder.Entity("Skill_Matrix.Entities.QuizResult", b =>
                {
                    b.Navigation("Suggestions");
                });

            modelBuilder.Entity("Skill_Matrix.Entities.Skill", b =>
                {
                    b.Navigation("QuizBatches");

                    b.Navigation("QuizResults");

                    b.Navigation("Suggestions");
                });

            modelBuilder.Entity("Skill_Matrix.Entities.User", b =>
                {
                    b.Navigation("QuizBatches");

                    b.Navigation("QuizResults");

                    b.Navigation("Skills");

                    b.Navigation("Suggestions");
                });
#pragma warning restore 612, 618
        }
    }
}
